def build_weighted_tgv_graph():
    weighted_graph = {
        'Paris': {
            'London': 2, 
            'Bruxelles': 1, 
            'Nantes': 2, 
            'Rennes': 1, 
            'La Rochelle': 3, 
            'Lyon': 2, 
            'Reims': 1, 
            'Lille': 1, 
            'Luxemburg': 2, 
            'Strasbourge': 2, 
            'Nancy': 2,
            'Geneve': 4,
            'Zurich': 5,
            'Frankfurt': 4,
            'Stuttgart': 3,
            'Bordeaux': 2,
        },
        'London': {
            'Paris': 2,
            'Lille': 2,
            'Bruxelles': 2,
        },
        'Lyon': {
            'Saint-Etienne': 1,
            'Marseille': 2,
            'Geneve': 2,
            'Paris': 2,
            'Zurich': 4,
            'Grenoble': 1,
            'Montpellier': 2,
        },
        'Marseille': {
            'Nice': 3,
            'Montpellier': 2,
            'Lyon': 2,
            'Grenoble': 3,
        },
        'Montpellier': {
            'Barcelona': 3,
            'Marseille': 2,
            'Grenoble': 3,
            'Lyon': 2,
        },
        'Barcelona': {
            'Montpellier': 3,
        },
        'Nice': {
            'Marseille': 3,
        },
        'Grenoble': {
            'Milano': 4,
            'Lyon': 1,
        },
        'Saint-Etienne': {
            'Lyon': 1,
        },
        'Milano': {
            'Grenoble': 4,
        },
        'Geneve': {
            'Paris': 4,
            'Lyon': 2,
            'Zurich': 3,
        },
        'Zurich': {
            'Paris': 5,
            'Lyon': 4,
            'Geneve': 3,
        },
        'Reims': {
            'Paris': 1,
            'Strasbourge': 2, 
            'Nancy': 2,
            'Frankfurt': 4,
            'Stuttgart': 3,
            'Luxemburg': 2,
        },
        'Luxemburg': {
            'Paris': 2,
            'Reims': 2,
            'Strasbourge': 2,
            'Nancy': 2,
            'Stuttgart': 3,
            'Frankfurt': 4,
        },
        'Nancy': {
            'Luxemburg': 2,
            'Reims': 2,
            'Paris': 2,
            'Frankfurt': 3,
            'Stuttgart': 3,
            'Strasbourge': 1,
        },
        'Frankfurt': {
            'Luxemburg': 4,
            'Reims': 4,
            'Paris': 4,
            'Stuttgart': 1,
            'Strasbourge': 2,
            'Nancy': 3,
        },
        'Stuttgart': {
            'Luxemburg': 3,
            'Reims': 3,
            'Paris': 3,
            'Strasbourge': 1,
            'Nancy': 3,
            'Frankfurt': 1,
        },
        'Strasbourge': {
            'Luxemburg': 2,
            'Reims': 2,
            'Paris': 2,
            'Colmar': 1,
            'Nancy': 1,
            'Frankfurt': 2,
            'Stuttgart': 1,
        },
        'Colmar': {
            'Strasbourge': 1,
        },
        'Lille': {
            'Paris': 1,
            'London': 2,
            'Bruxelles': 1,
        },
        'Bruxelles': {
            'Amsterdam': 2,
            'Lille': 1,
            'Paris': 1,
            'London': 2,
        },
        'Amsterdam': {
            'Bruxelles': 2,
        },
        'Rennes': {
            'Paris': 1,
            'Nantes': 1,
            'La Rochelle': 3,
            'Bordeaux': 4,
            'Saint-Malo': 1,
            'Quimper': 2,
            'Brest': 2,
        },
        'Saint-Malo': {
            'Rennes': 1,
            'Brest': 3,
        },
        'Brest': {
            'Rennes': 2,
            'Saint-Malo': 3,
        },
        'Quimper': {
            'Rennes': 2,
        },
        'Nantes': {
            'Paris': 2,
            'Bordeaux': 3,
            'La Rochelle': 2,
            'Rennes': 1,
        },
        'Bordeaux': {
            'Paris': 2,
            'Nantes': 3,
            'Rennes': 4,
            'La Rochelle': 2,
            'Hendaye': 3,
            'Pau': 2,
            'Toulouse': 2,
        },
        'La Rochelle': {
            'Bordeaux': 2,
            'Paris': 3,
            'Rennes': 3,
            'Nantes': 2,
        },
        'Toulouse': {
            'Bordeaux': 2,
            'Hendaye': 4,
            'Pau': 2,
        },
        'Pau': {
            'Bordeaux': 2,
            'Hendaye': 2,
            'Toulouse': 2,
        },
        'Hendaye': {
            'Bordeaux': 3,
            'Toulouse': 4,
            'Pau': 2,
        }
    }